#Fatiando um nome
nome = str(input('Digite seu nome completo: ')).strip()
print()
print('Nome em maiúsculas:')
print(nome.upper())
print()
print('Nome em minúsculas:')
aux = nome.lower()
print(aux)
print()
print('Quantidade de letras no nome sem espaços: ',len(nome) - nome.count(' '))
aux1 = nome.split()
print()
print('Quantidade de letras no primeiro nome: ',len(aux1[0]))
print()
print('O primeiro nome é: {} '.format(aux1[0]))
print()
print('O último nome é: {}'.format(aux1[-1]))
print()
aux2 = 'silva' in aux
print('Esse nome tem a palavra Silva?')
print(aux2)
